---
- name: create a cloudformation stack
  cloudformation:
    stack_name: "multiTierDevops"
    state: "present"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "us-east-1"
    disable_rollback: true
    template: "{{role_path}}/templates/multiTierApp.json"
    tags:
      Stack: "iamdevops"
  tags:
  - create

- name: delete a cloudformation stack
  cloudformation:
    stack_name: "multiTierDevops"
    state: "absent"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "us-east-1"
    template: "{{role_path}}/templates/multiTierApp.json"
    tags:
      Stack: "iamdevops"
  tags:
  - remove
