---

- name: Set fact vars
  set_fact:
    conf_file: "{{ deploy_home }}/libs/nginx/conf/{{application}}.conf"
    temp_conf_file: "{{ deploy_home }}/libs/nginx/conf/{{application}}-temp.conf"
    application_service_file: "{{role_path}}/templates/nginx-{{application}}.service.j2"
    BE_servers: "{{ groups['tag_App_BE']  }}"


- name: Create nginx log directory
  file:
    path: "{{ item.path }}"
    state: directory
    recurse: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: "{{ item.mode }}"
  with_items:
  - {path: "{{ nginx.logs_dir }}", mode: "0750"}
  - {path: "{{ pid_dir }}", mode: "0750"}
# service config files
- name: Create temp NGINX conf file for app
  template:
    src: "nginx-{{ application }}.conf.j2"
    dest: "{{ temp_conf_file }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Test nginx conf
  command: "{{ deploy_home }}/libs/nginx/sbin/nginx -t -c {{ temp_conf_file }}"
  become_user: "{{deploy_user}}"

- name: Update NGINX conf file for app
  copy:
    src: "{{ temp_conf_file }}"
    dest: "{{ conf_file }}"
    remote_src: yes
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

  # systemd service files
- name: "Create systemd file for nginx proxy service from {{ application_service_file }}"
  template:
    src: "{{application_service_file}}"
    dest: "/etc/systemd/system/nginx-{{ application }}.service"

- name: Start FE service
  systemd:
    name: "nginx-{{ application }}.service"
    state: restarted
    enabled: yes
